### ISSUE TITLE
Lesson 2.3 - completed code throws an unhandled NullReferenceException on exit

### ISSUE THREAD

**Issue by da9l** [petabridge/akka-bootcamp#108]
When running the completed code or the code I wrote following the guide I get an unhandled NullReferenceException in ChartingActor.cs in HandleMetrics (See comment below)

    private void HandleMetrics(Metric metric)
        {
            if (!string.IsNullOrEmpty(metric.Series) && _seriesIndex.ContainsKey(metric.Series))
            {
                var series = _seriesIndex[metric.Series];
                series.Points.AddXY(xPosCounter++, metric.CounterValue); // <- series.Points is null!
                while(series.Points.Count > MaxPoints) series.Points.RemoveAt(0);
                SetChartBoundaries();
            }
        }

I've managed to reproduce the problem when enabling all performance counters, disabling them and enabling them again and then exit the application.

**Comment by skotzko** [comment]
Thank you for submitting this. This shows up if you close the winforms app but don't stop debugging. However, not to fix as it doesn't materially impact the objective of these exercises (and this is just sample code anyway).
