### ISSUE TITLE
Markdown code samples not rendering correctly

### ISSUE THREAD

**Issue by ralfw** [petabridge/akka-bootcamp#11]
Code samples in the readme.md files are started with

```
```csharp
```
That seems to work well when displayed online in GitHub. But if I look at the .md file with a markdown editor like Mou it does not render well:

![bildschirmfoto 2015-02-23 um 12 21 16](https://cloud.githubusercontent.com/assets/132662/6326879/8cf7552e-bb56-11e4-95e8-26789e154f25.png)

So the question should really be: What to optimize the markdown for? GitHub or any other markdown editor/reader?

**Comment by Aaronontheweb** [comment]
The lessons are meant to be followed in Github, as we use Github-flavored markdown for syntax highlighting (done via Pygments.) We suggest following along using Github in a browser tab on the main README: https://github.com/petabridge/akka-bootcamp#use-github-to-make-life-easy

If you want a desktop editor that can render the markdown correctly, MarkdownPad2 (which we used to author the lessons) supports GFM. Sublime Text 2 / 3 also supports GFM preview using this plugin: https://github.com/revolunet/sublimetext-markdown-preview

**Comment by skotzko** [comment]
@ralfw I used to use Mou also but have since switched to [MacDown](http://macdown.uranusjr.com/). Open source OSX editor w/ GFM, excellent.

**Comment by ralfw** [comment]
@skotzko Thx for the tip. Will try MacDown.
