### ISSUE TITLE
Lesson 1.2: Defining and Handling Messages

### ISSUE THREAD

**Issue by garybond** [petabridge/akka-bootcamp#111]
Following lessons 1.1 and 1.2 from the email instructions leaves the program.cs Main with Actor creation like this:

var consoleWriterActor = MyActorSystem.ActorOf(Props.Create(() => new ConsoleWriterActor()));
    var consoleReaderActor = MyActorSystem.ActorOf(Props.Create(() => new ConsoleReaderActor(consoleWriterActor)));

This gave me a build error on the following line:
consoleReaderActor.Tell(ConsoleReaderActor.StartCommand);

"StartCommand" unable to resolve symbol.

The completed code example has the creation of the Actors with names being assigned to them:
            // make our first actors!
            IActorRef consoleWriterActor = MyActorSystem.ActorOf(Props.Create(() => new ConsoleWriterActor()),
                "consoleWriterActor");
            IActorRef consoleReaderActor =
                MyActorSystem.ActorOf(Props.Create(() => new ConsoleReaderActor(consoleWriterActor)),
                    "consoleReaderActor");

Which resolves the build issue, but doesn't explain why you need to pass in the second (name) parameter when creating your Actors.

**Comment by garybond** [comment]
Sorry, the build error was a typo:
I had:   consoleReaderActor.Tell(consoleReaderActor.StartCommand);
Needed to be:   consoleReaderActor.Tell(ConsoleReaderActor.StartCommand);

But there is still the disparity in the code being used in the email and that in the completed example.

**Comment by skotzko** [comment]
I just ran through it manually from the starter solution using the email instructions and am not able to recreate your issue. Your build error sound like it's related to namespacing.

Using `var` or `IActorRef` on the `consoleWriterActor` and `consoleReaderActor` assignments have no impact so you can ignore. Passing the name as the second parameter is optional, but is a *very* good habit to get into (as we explain later in bootcamp).
