### ISSUE TITLE
Lesson 3.3 - Strange sentence in lesson (maybe just uncompleted)

### ISSUE THREAD

**Issue by kpa6uk** [petabridge/akka-bootcamp#112]
See this section:
https://github.com/petabridge/akka-bootcamp/tree/master/src/Unit-3/lesson3#how-do-i-use-the-hocon-config 

The only sentence in this section starts with small letter and has no point at the end. It is too complex for understanding either.

**Comment by skotzko** [comment]
Weird, dunno how we missed that in edits. Thanks for the heads up.
