### ISSUE TITLE
Difficult Naming in 3.1

### ISSUE THREAD

**Issue by pettys** [petabridge/akka-bootcamp#114]
I'm trying to make sense of the code as I'm going through it, and am really stumbling over how things are named. The two things that create ambiguity are:

 * We have `GithubCommanderActor` and `GithubCoordinatorActor`. I'm trying to reason in my mind about what might be the difference between something that "commands" and something that "coordinates." I don't think this is very clear. To make the point, the comment for Github**Commander**Actor says, "Top-level actor responsible for *coordinating*...".

* For the commander's messages, we've got `CanAcceptJob` and `AbleToAcceptJob`. Again, just looking at these names, it's hard to distinguish what they are used for -- seems like two ways of saying the same thing. I'm pretty sure that "can" and "able to" are exactly synonymous. This makes it hard to comprehend what `GithubCommanderActor` is doing as I read through the code.

Could these names be changed to something more descriptive that could be used to help a newcomer to the code follow along? If something occurs to me when I reach the end of the lesson I'll update this issue.

**Comment by pettys** [comment]
After finishing the lesson, and then browsing the code some more and checking the diagrams, I'm seeing what things are for:

 * `GithubCoordinatorActor` is responsible for handling a single "job." A name like `GithubJobCoordinator` or `DownloadFromGibhubCoordinator` would clarify.

 * `CanAcceptJob` is meant to *ask* someone the question, "Can you accept this job?" and `AbleToAcceptJob` is the response, "Yes, I can accept that job." I think name changes like this would help newcomers quite a bit:

   * `CanAcceptJob` => `CanYouAcceptThisJob`
   * `AbleToAcceptJob` => `JobAccepted`
   * `_canAcceptJobSender` => `_jobRequestor` (in `GithubCommanderActor`)

I realize that renaming various things would be pretty time intensive (images, readmes, and several solutions). I think some naming changes internal to GithubCommanderActor would have helped a lot -- I'll create a pull request for these.

**Comment by skotzko** [comment]
Thanks for your feedback on this, and I appreciate you submitting a PR. However, is not an isolated change to this lesson—it affects the entire unit. 

While I agree that the naming could be improved, it is not a significant enough improvement to rewrite the entire unit (the concepts are what matters, not the specific names of actors in our demo code). If you'd like this changed, please submit a PR updating the entire unit at once accordingly and we'll review.
