### ISSUE TITLE
Readme for lesson 3.3 has an unclear section

### ISSUE THREAD

**Issue by pettys** [petabridge/akka-bootcamp#119]
Lines 91-93 of Unit-3\lesson3\README.md looks like this:

```
#### How do I use the HOCON config?
setting up router needs a router config
as long as the router config passed isn't "no router" then it will
```

This is not written as a complete sentence; I actually have no idea what is meant.

**Comment by skotzko** [comment]
Was handled in a separate commit, forgot to include this issue # in the fix message
