### ISSUE TITLE
Lesson 1.2 - casting

### ISSUE THREAD

**Issue by MaciekLesiczka** [petabridge/akka-bootcamp#122]
There is no need to cast message object when it is told actor.
This
```
            else if(message is Messages.InputError)
            {
                _consoleWriterActor.Tell(message as Messages.InputError);
            }
```
gives the same result as
```
            else if(message is Messages.InputError)
            {
                _consoleWriterActor.Tell(message);
            }
```

**Comment by skotzko** [comment]
Yeah, you're right @MaciekLesiczka. I can't remember why we did it that way, probably just got overlooked. 

However, as this has zero impact and this is just sample code anyway, it's not worth changing. Please feel free to submit a PR that updates this if you'd like.
