### ISSUE TITLE
Can't run Unit 2 code in Xamarin on OS X

### ISSUE THREAD

**Issue by mrn-aglic** [petabridge/akka-bootcamp#123]
There is a problem with running the code for Unit 2 in Xamarin on OS X Yosemite, the application cannot run. 

Any workarounds or gtk# alternative?

**Comment by skotzko** [comment]
None at this time that I know of, unfortunately. @Aaronontheweb you know any?

**Comment by Aaronontheweb** [comment]
Nope, the data visualization components I used aren't supported on Xamarin.
