### ISSUE TITLE
Lesson 1.1 gramma

### ISSUE THREAD

**Issue by Silv3rcircl3** [petabridge/akka-bootcamp#124]
In the part "What is an actor"
>everything is an object in OOP, in the actor modeleverything is an actor.
Repeat this train of thought to yourself. 

modeleverything needs a space -> model everything
And after the sentence there should be properly another newline ;-) 

![image](https://cloud.githubusercontent.com/assets/6583600/7887193/b33ddc98-062f-11e5-82dc-4b829f208c0f.jpg)

**Comment by skotzko** [comment]
Thanks. Got it fixed in the email.
