### ISSUE TITLE
NullReferenceException sometimes occurs

### ISSUE THREAD

**Issue by mrn-aglic** [petabridge/akka-bootcamp#126]
Hello, 
Just passed lessons 3 and 4, noticed that a NullReferenceException sometimes occurs in ChartingActor in method HandleMetrics on series.Points object. This exception occurs when closing the application.

**Comment by Aaronontheweb** [comment]
This comes from the `ChartingActor` still writing to the Charting component after the form is starting to close. I should be able to fix this by explicitly killing the actor and shutting down the `ActorSystem` on the Form_Closing event. I'll go add that.
