### ISSUE TITLE
Invalid syntax for creating a child actor in lesson 1.4

### ISSUE THREAD

**Issue by jorgef** [petabridge/akka-bootcamp#13]
ActorOf is not a method of ActorRef.

```cs
// create the children of actor a2
ActorRef b1 = a2.ActorOf(Props.Create<BasicActor>(), "b1");
ActorRef b2 = a2.ActorOf(Props.Create<BasicActor>(), "b2");
```
Link: https://github.com/petabridge/akka-bootcamp/tree/master/src/Unit-1/lesson4#actor-path--actor-position-in-hierarchy

**Comment by skotzko** [comment]
Thanks @jorgef. We missed this and will fix soon.
