### ISSUE TITLE
DropBox blocked at work

### ISSUE THREAD

**Issue by showens** [petabridge/akka-bootcamp#131]
Sites such as OneDrive and DropBox are blocked at my company.  It might be nice to offer an alternative for those of us in Internet Jail.

**Comment by JulienFiaffe** [comment]
I had the same problem when starting a new Unit. Then I chose to download the code directly from GitHub (with the "Download ZIP" option). I did not have any issue by doing this.

**Comment by showens** [comment]
Thanks, JulienFiaffe. That's what I ended up doing.  Perhaps there could be a comment to that effect in the initial email message where the DropBox link is.
