### ISSUE TITLE
Lesson 3.2 (Pool Router) - Octokit.ForbiddenException

### ISSUE THREAD

**Issue by JulienFiaffe** [petabridge/akka-bootcamp#133]
Hello,
In Unit 3, Lesson 2, after using the pool router to accelerate the job I discovered that the tool was unable to complete the fetch for some repositories.
It is annoying since it cannot allow us to see the performance difference for the entire process.
After investigation I saw that it comes from an Octokit.ForbiddenException with the following message:

"You have triggered an abuse detection mechanism and have been temporarily blocked from calling the API. Please retry your request again later."

It makes sense and I'm not sure that is a real issue. I just wanted to let you know about that.
Maybe I missed something or it could be a good idea to detect these kind of errors and notify the user.

If you need more information let me know!

**Comment by skotzko** [comment]
Yeah, we've seen this before and alerted Github about it. Unfortunately there's nothing we can do about it for now. Thanks for the info!
