### ISSUE TITLE
Lesson 1 has DeathWatchNotification issue when exiting

### ISSUE THREAD

**Issue by CreepyGnome** [petabridge/akka-bootcamp#140]
If you type anything but exit, and then type exit I get a DeathWatchNotification when the shutdown occurs. 

1.  Open solution from https://github.com/petabridge/akka-bootcamp/tree/master/src/Unit-1/lesson1/Completed
2. Run start up project
3. type foo
4. hit enter
5. type exit
6. hit enter
7. DeathWatchNotifcation will be displayed during shutdown

**Comment by CreepyGnome** [comment]
This is in the last lesson of unit 1 as well when you just type exit instead of providing a URL path to a file, so may be in all lessons of unit 1.

**Comment by BrainSlugs83** [comment]
This seems to happen to me in every lesson of Unit 1 as well.  (whether I "exit" before providing a file path or not.) -- Is the Notification bad? -- It seems pretty ubiquitous so far, so I just assumed it was normal.
