### ISSUE TITLE
Blocking an Actor in Unit-3/lesson2

### ISSUE THREAD

**Issue by pandarun** [petabridge/akka-bootcamp#149]
As I understand actors Receive delegate should be non blocking.

var getStars = _gitHubClient.Activity.Starring.GetAllStargazers(starrers.Owner, starrers.Repo);

//ewww
getStars.Wait();

So the question is how to code non blocking io operation, e.g http request, and another question
is how to code cpu intensive tasks with actors.

Thank you!

**Comment by Aaronontheweb** [comment]
> As I understand actors Receive delegate should be non blocking.

The `Receive` method should always block until all internal state of an actor has finished being modified for that particular message. Waiting on a Task is one way to do it; async / await is another; but the best option is to use `PipeTo` and pipe the object returned by a `Task<T>` as a new message into the actor.
