### ISSUE TITLE
Lesson 2.1: - need to install nuget packages

### ISSUE THREAD

**Issue by tsaaugaard** [petabridge/akka-bootcamp#184]
The text does not (re)state how to install nuget packages for the solutions, found this to work:
PM> Install-Package Akka -version 1.0.6
PM> Install-Package System.Collections.Immutable -Version 1.1.36

**Comment by Aaronontheweb** [comment]
Good catch - I'll need to update this

**Comment by tsaaugaard** [comment]
Thanks :-)
