### ISSUE TITLE
Lesson 1.4, File Validation OnReceive disallows further input

### ISSUE THREAD

**Issue by JDLessl** [petabridge/akka-bootcamp#193]
In the FileValidatorActor.OnReceive() method, the call to Sender.Tell() is only run in the event of bad input.  If the path is good, then the Console.ReadLine() in ConsoleReaderActor is never run again, and you can't exit out by typing "exit".

**Comment by Aaronontheweb** [comment]
Once the tail call begins in earnest you can only exit the program by pressing Control + C, just like the real commandline `$ tail -f ` option. So I don't think this is a "bug," but perhaps a miscommunication in the documents.
