### ISSUE TITLE
What scopes does the lab need for GitHub OAuth token

### ISSUE THREAD

**Issue by khtan** [petabridge/akka-bootcamp#201]
In Akka.NET Bootcamp - Unit3, ( https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-3/README.md ), under the "Things you'll need", there is a link to "Follow the instructions here" to get an OAuth access token. There is no mention of what scopes should be selected for the purpose of the labs.

**Comment by izavala** [comment]
I can see how this can be confusing and will update this to specify that you only need to set the scope to repo.

**Comment by mika76** [comment]
Yeah this definitely should be stated...

**Comment by izavala** [comment]
Thank you guys, this has now been updated:
