### ISSUE TITLE
Lesson 1.1 (Immediately closes after starting application)

### ISSUE THREAD

**Issue by sverro2** [petabridge/akka-bootcamp#209]
After "thoroughly" replicating the first lesson, the application will immediately exit after running the application. This can be fixed when adding "MyActorSystem.WhenTerminated.Wait();" at the end of the main function (this solution is also used in the 'Completed' code of this lesson.). The lesson itself doesn't mention this (rather important) step...

**Comment by izavala** [comment]
The line of code `MyActorSystem.WhenTerminated.Wait();` will be needed to prevent the console window from closing as it will not be executed until the Actor System closes. This is included in the DoThis file that will be used for this exercise. 

https://github.com/petabridge/akka-bootcamp/blob/2e72b45f3f050d9b76ed51f3e3c613a202e13407/src/Unit-1/DoThis/Program.cs#L9-L28

**Comment by skydvr** [comment]
Not sure what I'm doing wrong, but my src\Unit-1\DoThis\Program.cs (which is included when I open src\Unit-1\DoThis\WinTail.sln) is simply 2 "using" directives and an empty namespace declaration.  No class definition, no methods, no var definitions - nothing.
