### ISSUE TITLE
Deprecated code: ActorSystem.Shutdown

### ISSUE THREAD

**Issue by FoggyFinder** [petabridge/akka-bootcamp#212]
In [this](https://github.com/petabridge/akka-bootcamp/blob/FSharp/src/Unit-1/FSharp/lesson1/Completed/Actors.fs#L23) line used deprecated code.

It is recommended to use the method [`Terminate`](http://api.getakka.net/docs/stable/html/1D77975.htm) instead of [`Shutdown`](http://api.getakka.net/docs/stable/html/99D4FF96.htm). 

But it's returns `Task`, not `unit`, so we should use something like that :

```fsharp
            mailbox.Context.System.Terminate() 
            |> Task.WaitAll
```
instead?

**Comment by Aaronontheweb** [comment]
@FoggyFinder yes we should update it to use `System.Terminate` instead

**Comment by FoggyFinder** [comment]
Have you any plans to update the source code?
