### ISSUE TITLE
Actor class Factory method throws exception in AKKA.Net Props.Create()

### ISSUE THREAD

**Issue by Phil-Debbs** [petabridge/akka-bootcamp#213]
I tried creating an actor by passing the factory method of the actor class to the Props.Create lambda, 

            MyActorSystem = ActorSystem.Create("MyActorSystem");

            var _writer = MyActorSystem.ActorOf(Props.Create(() => ConsoleWriterActor.GetInstance()), "writer");

but it throws  

"System.InvalidCastException"

**Comment by Aaronontheweb** [comment]
Answered this via email but it bears repeating here:

Ah, I see what’s going on here. Using this syntax `Props.Create(() => new ...)` we’re looking for a new expression to use so `Props` can memorize the actor’s type, constructor signature, and arguments. By putting in a static factory method instead this is no longer a new expression and is just a standard void delegate expression instead. Hence the reason for this error. The function you pass into props is never actually called. It just tells Akka.NET how to construct your actor. Does that make sense?
