### ISSUE TITLE
broken url in akka bootcamp unit 2 lesson 1 

### ISSUE THREAD

**Issue by pavsh** [petabridge/akka-bootcamp#237]
hi,
the url to : 
http://getakka.net/docs/concepts/configuration 
 Is broken.
seams like all the documentation in the getakka.net has changed.

**Comment by pavsh** [comment]
the url is the link  of " HOCON configuration in Akka.NET " sentence

**Comment by nathvi** [comment]
@pavsh , this was fixed in #254 .
@Aaronontheweb , this should be closed.

**Comment by izavala** [comment]
https://github.com/petabridge/akka-bootcamp/pull/254
