### ISSUE TITLE
FileSystemWatcher() issues in Xamarin/Mono

### ISSUE THREAD

**Issue by laz0rviking** [petabridge/akka-bootcamp#25]
Currently working Bootcamp in a Xamarin/Mono 3.12.0 environment. In Lesson 1.4 there's a problem with `FileSystemWatcher()` which has been a nuisance bug to the Mono community for a while where the `Changed` state is never passed. Here's the Bugzilla: https://bugzilla.xamarin.com/show_bug.cgi?id=19741

The following is a partial workaround but I haven't had time to properly debug it. This workaround allows for the `Changed` state to pass but then it seems something might not be working with `TailActor()`. The workaround is discussed here: http://stackoverflow.com/questions/16859372/why-doesnt-the-servicestack-razor-filesystemwatcher-work-on-mono-mac-os-x

The workaround -- in `FileObserver.cs` -> `Start()`, before the `_watcher = new FileSystemWatcher(...)`, insert
```
// Need this for Mono 3.12.0 workaround
Environment.SetEnvironmentVariable("MONO_MANAGED_WATCHER", "enabled");
```

Haven't hide time to follow through but I know I need to at least drop this here! Will check back in later this evening and try some more debugging.

**Comment by skotzko** [comment]
@laz0rviking any issues for you w/ 1.5 & 1.6, if you've gotten to those yet?
