### ISSUE TITLE
Refactor ValidationActor to be sender agnostic

### ISSUE THREAD

**Issue by nathvi** [petabridge/akka-bootcamp#264]
I may be missing something, but wouldn't it be better for the ValidationActor to not have any reference to the ConsoleWriterActor? When it gets a message it can handle, shouldn't it be `Tell`ing the sender some message? For example:

```csharp
//In the OnReceive method of ValidationActor
//...
if (string.IsNullOrEmpty(msg))
{
        // signal that the user needs to supply an input
        _consoleWriterActor.Tell(
        new Messages.NullInputError("No input received."));
}
```

could be refactored as:

```csharp
//In the OnReceive method of ValidationActor
//...
if (string.IsNullOrEmpty(msg))
{
        // signal that the user needs to supply an input
        Sender.Tell(
        new Messages.NullInputError("No input received."));
}
```

**Comment by izavala** [comment]
The empty message will be coming in from the `ConsoleReaderActor`, which does not have a way to print a message back to to console. When an empty message is received by the `FileValidatorActor` from the `ConsoleReaderActor`, it will send a message to the `ConsoleWriterActor` to inform the user and let them know we did not receive a message.
