### ISSUE TITLE
Lesson 2.3 Step 5 relies on yet to be created RemoveSeries message

### ISSUE THREAD

**Issue by mattherman** [petabridge/akka-bootcamp#266]
In Step 5 of Lesson 2.3, the `Unwatch` receiver attempts to send the `RemoveSeries` message to the charting actor, but that message type is not added until Step 7 of this lesson.

**Comment by izavala** [comment]
To help things not become too confusing, step 5 focuses on creating the `PerformanceCounterCoordinatorActor`. At the end of step 5 it is not quite ready to use just yet. As there are a couple of changes that need to be done to the `ChartingActor`, step 7 will focus on updating all of the messages and behavior on this Actor.
