### ISSUE TITLE
Unit 3 requires the sample solution's Octokit version to be upgraded

### ISSUE THREAD

**Issue by drahcrom** [petabridge/akka-bootcamp#268]
When attempting to access github using the key generated following the steps the application fails. 

Updated OctoKit and then it works as expected.

I belive it might be related to this github notice:
https://developer.github.com/changes/2018-02-01-weak-crypto-removal-notice/

**Comment by heatonmatthew** [comment]
I believe that this is also the same issue as #273.

**Comment by izavala** [comment]
Boot camp is not set to use 0.32.0 and should allow for authentication.
