### ISSUE TITLE
Unit 3, Lesson 1 - GitHub API Authorization Failing

### ISSUE THREAD

**Issue by MitoniKatsu** [petabridge/akka-bootcamp#273]
When running the solution, I was running into an issue with token authorization failing. When I drilled deeper into it, I found that the .net web request was throwing:

"The request was aborted: Could not create SSL/TLS secure channel."

After looking into it further, I found that it was trying to use an older TLS version, which the gitHub API stopped supporting as of earlier this year (it was using TLS 1.0).  I was able to resolve this by adding the following to the main method (quick and dirty fix).

    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

After that, it connected without issue (using TLS 1.2).

**Comment by DonaldWebb** [comment]
I ran into the same issue. Windows 10.
Updating Octokit to 0.32.0 resolved the issue. https://www.nuget.org/packages/Octokit/0.32.0

**Comment by Aaronontheweb** [comment]
@DonaldWebb thanks for reporting that! We should probably patch it, although I'm considering re-writing this lesson altogether since using the Github API has become more onerous than it was a few years ago when I originally wrote this.

**Comment by heatonmatthew** [comment]
@Aaronontheweb I notice that this issue has been open for a while and understand that you're considering re-writing the unit.  In the interim it might be helpful to do a simple fix (upgrade to Octokit 0.32.0 or even just upgrade to net462 works)?

Would it help if I submitted a Pull Request with an appropriate change?

**Comment by metat8** [comment]
I'm running into the same issue.  I've tried upgrading to Octokit 0.32.0 and it hasn't fixed the issue.  Does anyone know what file I need to add the quick and dirty fix that @MitoniKatsu suggested?  You said main method- which main method or more specifically which file did you add that to for it to work???
@Aaronontheweb Please update the solution so we all don't have to spend hours prepping for Unit 3.

**Comment by metat8** [comment]
"We should probably patch it, although I'm considering re-writing this lesson altogether since using the Github API has become more onerous than it was a few years ago when I originally wrote this."
Please patch or fix.  It's unusable currently.

**Comment by heatonmatthew** [comment]
@metat8 reading through my comment above I realise that I wasn't clear.  Upgrading the project to net462 (or above) got me connecting to github even without upgrading OctoKit.  Hopefully that helps you over the immediate hump if you're still stuck.

**Comment by izavala** [comment]
@metat8 If you download the latest version of Bootcamp are you still unable to authenticate?
