### ISSUE TITLE
Lesson 3.1 Missing Field Declaration

### ISSUE THREAD

**Issue by Jumble123** [petabridge/akka-bootcamp#277]
The following declaration - which is missing from the instructions in Lesson 3.1 - is required in GithubCommanderActor:

private IActorRef _coordinator;

**Comment by izavala** [comment]
I can see how this may be confusing, however if you are starting your solution from the DoThis folder, this has already been declared for you in the following code: 

https://github.com/petabridge/akka-bootcamp/blob/2e72b45f3f050d9b76ed51f3e3c613a202e13407/src/Unit-3/DoThis/Actors/GithubCommanderActor.cs#L47-L54
