### ISSUE TITLE
Unit 3 Issues out of the box

### ISSUE THREAD

**Issue by metat8** [petabridge/akka-bootcamp#281]
I've just started the Unit 3 pre work of making sure I'm able to pass the github access token but everytime I try I with an access token I get "Authentication failed. Please try again."   I tried some of the suggestions in #273 and #268 but nothing fixes it.  I spoke with someone in my office who tried this training in July 2018 and he had the same issue and wasn't able to fix.  I think AKKA.Net is pretty cool so far but not being able to start Unit 3 is really frustrating.  I'm open to any suggestions that will allow me to continue my training.

**Comment by metat8** [comment]
Here is a picture of the GitHub Access Token failing out of the box for Unit 3:

![unit_3_dothis_broken_out_of_box](https://user-images.githubusercontent.com/46939549/51770159-a5d15780-20aa-11e9-8124-8f00b7aa2ce6.png)

**Comment by Antonf26** [comment]
Did you update the Octokit nuget package?

**Comment by izavala** [comment]
The PR https://github.com/petabridge/akka-bootcamp/pull/287 sets the Bootcamp projects to use the Octokit version="0.32.0" NuGet package and should allow you to be authenticated.
