### ISSUE TITLE
Links to docs is broken in akka bootcamp unit1 lesson4

### ISSUE THREAD

**Issue by ecmtree** [petabridge/akka-bootcamp#296]
The docs link to One-For-One strategy presently points to http://getakka.net/docs/Supervision#one-for-one-strategy-vs-all-for-one-strategy
which does not lead to the doc instead says that "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.". Same is true for docs link for Restart directive.

It should point to the following correct links 
**One-For-One strategy** 
https://getakka.net/articles/concepts/supervision.html#one-for-one-strategy-vs-all-for-one-strategy
**Restart directive**
https://getakka.net/articles/concepts/supervision.html#what-restarting-means

Kindly correct the links. It would be helpful for others.

**Comment by skydvr** [comment]
Simple fix, so I submitted a pull request for this:
https://github.com/petabridge/akka-bootcamp/pull/300

**Comment by Aaronontheweb** [comment]
closed via #300
