### ISSUE TITLE
File change not displayed on Mono/OS X

### ISSUE THREAD

**Issue by timba** [petabridge/akka-bootcamp#36]
When running this under Mono on OS X (10.9.5), FileStream doesn't read file to the end after modification saved. As a result TailActor doesn't notify _reporterActor about changes. This line always gets empty string:

```CSharp
var text = _fileStreamReader.ReadToEnd();
```

https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-1/lesson4/Completed/TailActor.cs#L92

It looks like Mono issue.

**Comment by skotzko** [comment]
@timba did you uncomment the environment variable as noted? See this line >> https://github.com/petabridge/akka-bootcamp/blob/08c90e8874def4c68626174d9336e28fecb43552/src/Unit-1/lesson4/Completed/FileObserver.cs#L33

**Comment by timba** [comment]
Yes I did. There is no problem with file changes watching: FileObserver's _watcher.Changed raised each time a file is changed. The problem is with TailActor's _fileStream which doesn't read any more after change notification received from FileObserver.

**Comment by skotzko** [comment]
@timba Hmm. That's odd. Will take a look.

**Comment by alistair** [comment]
@timba how are you writing to the file?   I have noticed that if I use kwrite then the change event from the watcher is raised,  but the stream reads and empty string,  as you have observed.

But it works perfectly fine if I re-start the application and use bash to write to the file

    echo "Hello World" >> file.log

On a similar but different note I had the similar issues in windows in that notepad and sublime kept saying the file was locked.  bash to the rescue again there.

**Comment by timba** [comment]
Thanks @alistair,

For file modification I used native Mac TextEdit editor. I tried your bash echo to the file redirection and it worked perfectly: FileStream was able to read appended lines. This is a workable workaround for me.

So it looks like the problem is in dissimilarities of file IO system internals behavior between Mono on Linux/Mac and Windows. In my Windows Mono version file changing and saving via Notepad was correctly handled and reported by TailActor.

I'll try to make additional tests and see if it is possible to track file changes via FieStream same way on multiple systems. If I find something I'll let you know via change request. But this issue I believe could be closed. You could only mention in https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-1/lesson4/README.md ```echo``` file changing workaround for Linux/Mac.

P.S. My Mac Mono is almost the same as your Linux setup:
```
$ mono --version
Mono JIT compiler version 3.12.0 ((detached/b8f5055 Wed Feb 18 15:44:03 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/5486eb2)
	GC:            sgen
```

**Comment by skotzko** [comment]
@timba any updates here? I was able to have this run just fine today when I was verifying that everything still worked after fixing another bug

**Comment by timba** [comment]
@skotzko, behavior is the same. When running under Mono on Windows, the app intercepts edits made by text programs, like Notepad. When running on Mac/Linux, the app reacts only on pipe IO redirection to the file. I tried different combinations of FileStream options but no change.

**Comment by skotzko** [comment]
@timba can you delete whatever you currently have, and re-fork from master and try again? wondering if you have an old version

**Comment by uprun** [comment]
Hello to all, I have encountered the same issue on Linux Ubuntu 14.04, this issue occurs because when you are using some editor the text file is replaced, so you need to close current StreamReader and open it again, as proof of my words you can run bash command:
tail -F "logfileName"
and check its output when you are editing text with editor. You will see something like this:
tail: ‘some.log’ has been replaced;  following end of new file
to deal with this  i have modified code of OnReceive method in TailActor:
protected override void OnReceive(object message)
		{
			if (message is FileWrite)
			{

				// check if file on the disk is same size as loaded info about it in _fileStream
				// if not then just reload file 
				FileInfo info = new FileInfo (Path.GetFullPath(_filePath));
				if (info.Length > _fileStream.Length) {
					_reporterActor.Tell(string.Format("File was replaced, so it will be reloaded."));
					// save current readed amount of data
					long currentLocation = _fileStream.Length - 1 ;
					_fileStreamReader.Close ();
					_fileStream = new FileStream(Path.GetFullPath(_filePath), FileMode.Open, FileAccess.Read,
						FileShare.ReadWrite);
					// set position in file after readed data
					_fileStream.Seek (currentLocation, SeekOrigin.Begin);
					_fileStreamReader = new StreamReader(_fileStream, Encoding.UTF8);


				}
				var text = _fileStreamReader.ReadToEnd();
				if (!string.IsNullOrEmpty(text))
				{
					_reporterActor.Tell(text);
				}

			}
			else if (message is FileError)
			{
				var fe = message as FileError;
				_reporterActor.Tell(string.Format("Tail error: {0}", fe.Reason));
			}
			else if (message is InitialRead)
			{
				var ir = message as InitialRead;
				_reporterActor.Tell(ir.Text);
			}
		}


of course you need also remove readonly attribute from variables _fileStream and _fileStreamReader .
