### ISSUE TITLE
Typo's and 'bugs' in lesson 2.3

### ISSUE THREAD

**Issue by Danthar** [petabridge/akka-bootcamp#46]
I will enumerate all the things I noticed in this lesson.

In no particular order:
 - High level overview image points to the wrong url: It should be: https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-2/lesson3/images/system_overview_2_3.png
 - In the introduction to scheduling a code snippet contains the wrong code to access the scheduler from inside an actor: It says: Context.System.system.Scheduler.ScheduleOnce() where it should obviously be: Context.System.Scheduler.ScheduleOnce() 
 - I noticed one grammar error. This sentence is wierd: "Scheduled messages become are scheduled onto the CLR threadpool and use Task.Delay under the hood. "

Thats it :)

**Comment by skotzko** [comment]
@Danthar thanks! I'll handle shortly.
