### ISSUE TITLE
Proxy Servers...

### ISSUE THREAD

**Issue by bazhirani** [petabridge/akka-bootcamp#51]
Hi,
I'm working behind a proxy and I had issues connecting to github using octokit. I managed to solve this issue by adding the following settings to the configuration file.
  &lt;system.net&gt;
    &lt;defaultProxy useDefaultCredentials="true" /&gt;
  &lt;/system.net&gt;

**Comment by Aaronontheweb** [comment]
Thanks @bazhirani ! We'll include a mention of this in the Unit 3, lesson 1 readme
