### ISSUE TITLE
Problem with "create an issue" link in emails

### ISSUE THREAD

**Issue by softwaremike** [petabridge/akka-bootcamp#80]
At the bottom of the lessons is a paragraph that says:

> If there is a problem with the code running, or something else that needs to be fixed in this lesson, please **create an issue** and we'll get right on it. This will benefit everyone going through Bootcamp.

The "create an issue" link is invalid for the three lessons I've received so far.  It takes me to a GitHub 404 page.

**Comment by Maximusya** [comment]
Markdown translates url \[/issues\] (found in every README.md) to https://github.com/petabridge/akka-bootcamp/blob/master/issues, while the valid link is https://github.com/petabridge/akka-bootcamp/issues.

In this case absolute url would be absolutely ok, I think. No point playing with ../../ thing - unless you want to let forks to track their own issues.
