### ISSUE TITLE
Unit-3/lesson3 states that Ask is blocking operation

### ISSUE THREAD

**Issue by kekekeks** [petabridge/akka-bootcamp#83]
>NOTE: Ask is a blocking, synchronous operation.

http://api.getakka.net/docs/stable/html/E25BBF1C.htm
http://api.getakka.net/docs/stable/html/4BD93F0C.htm
As I can see, both extension methods return Task, which can be awaited inside [RecieveActor](http://api.getakka.net/docs/stable/html/5C8C7532.htm). So this is probably outdated.

**Comment by kekekeks** [comment]
3.4 states that we should use PipeTo, because await is not supported. Probably also outdated.

**Comment by skotzko** [comment]
Right you are. Not sure how that got in there. Thanks for catching that!
