### ISSUE TITLE
Exercise not fully explained 

### ISSUE THREAD

**Issue by pawelklimczyk** [petabridge/akka-bootcamp#88]
Exercise Uint3/Lesson2 (https://github.com/petabridge/akka-bootcamp/tree/master/src/Unit-3/lesson2) is not fully explained.
Programming steps in lecture do not cover all changes in GithubCommanderActor.
Thanks good I can use code from "Completed" folder.

**Comment by Aaronontheweb** [comment]
@pawelklimczyk I just used WinMerge to compare the output of Lesson1/Completed and Lesson2/Completed, and all of the steps needed to transform 1 into the other are fully explained in the lesson2 readme as verified by WinMerge.

What changes are missing?

**Comment by pawelklimczyk** [comment]
By "not fully explained" I do not mean some other akka techniques not introduces before.
What I mean is:
In Unit3/lesson2 description it is for example not explained where _githubWorker is declared.
I know (from "Completed" folder) where it should be. The point is that all previous lessons were like copy-paste from the lesson's description into IDE. All variables etc. were in place automatically ;)

**Comment by Aaronontheweb** [comment]
`_githubWorker` is present in the `GithubCoordinator` actor as a private field in the very beginning - in the initial files inside the `DoThis` folder. This variable was already in-place.

https://github.com/petabridge/akka-bootcamp/blob/master/src/Unit-3/DoThis/Actors/GithubCoordinatorActor.cs#L65

**Comment by pawelklimczyk** [comment]
Thanks! it seems I missed something.
