### ISSUE TITLE
Stashing description in 1.4 might be wrong

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/akka-bootcamp#93]
https://github.com/petabridge/akka-bootcamp/blob/8391bc4782c6a29f41ea2e01c31de179b04e65cc/src/Unit-1/lesson4/README.md#but-what-happens-to-the-current-message-when-an-actor-fails - this may not be technically correct. Need to investigate.

**Comment by skotzko** [comment]
@Aaronontheweb find anything on this?
