### ISSUE TITLE
Lesson 2.4 - confusing presentation of Become/BecomeStacked

### ISSUE THREAD

**Issue by jphorvath** [petabridge/akka-bootcamp#94]
The whole section starting with **Use Become to adopt a new behavior** confused me for a minute - the animated diagrams of how the stack works are labled `Become(...)`, not `BecomeStacked(...)`.  There is also a note saying `Become` will delete the old behavior off the stack, making me wonder what the deal was with all this stack talk if it always deletes the previous top?!

It was just confusing for a bit - maybe explicitly say early on there are 2 variations - `Become()` clears the stack and pushes, `BecomeStacked()` just pushes?

**Comment by skotzko** [comment]
@jphorvath ah, I see your point. No, we forgot to update the diagrams for the new behavior labels when 1.0 shipped. We'll get that fixed soon.
